### ISSUE TITLE
License

### ISSUE THREAD

**Issue by paulfantom** [donat-b/ansible-restic#11]
Please add a LICENSE file. Saying "BSD" in readme doesn't help since there are two BSD licenses (2-clause) and (3-clause).
github has a good and simple guide of adding license file: https://help.github.com/articles/adding-a-license-to-a-repository/

**Comment by paulfantom** [comment]
Worth mentioning: https://choosealicense.com/

**Comment by donat-b** [comment]
I think I'll keep it simple and make it BSD-2.
